apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName | quote }}
  namespace: {{ .Release.Namespace | quote }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-reader
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [list]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-reader
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName | quote }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-reader
